name: Update AUTHORS
on:
  push:
    branches:
      - master
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update authors
          title: Update test.txt
          body: Credit new contributors by updating vuong
          branch: update-authors